[plugin_opts]
args_dump = true

[SampleInfo.in]
infile = [ "data/samples.txt" ]

[SeuratPreparing.envs]
ncores = 4
cell_qc = "nFeature_RNA > 200 & percent.mt < 10 & percent.ribo > 5"
gene_qc = { min_cells = 0 }

[SeuratClustering.envs]
ncores = 4
cache = "./.cluster_cache"

[SeuratClustering.envs.FindClusters]
# 34 clusters
# resolution = [1.2, 1.3, 1.4, 1.5, 1.42]
resolution = [2.4, 2.5, 2.6, 2.7, 2.8]

[ModuleScoreCalculator.envs.modules.DC]
kind = "diffmap"
k = 20
n_pcs = 30
features = 5

[ModuleScoreCalculator.envs.modules.Treg]
features = [
    "NT5E", "CD3D", "CD3G", "CD3E", "CD4", "CD5", "ENTPD1", "CTLA4",
    "IZUMO1R", "TNFRSF18", "IL2RA", "ITGAE", "LAG3", "TGFB1", "LRRC32", "TNFRSF4",
    "SELL", "FOXP3", "STAT5A", "STAT5B", "LGALS1", "IL10", "IL12A", "EBI3", "TGFB1",
]

[ModuleScoreCalculator.envs.modules.CD8TCellActivation]
features = [
    "CD69", "CCR7", "CD27", "BTLA", "CD40LG", "IL2RA", "CD3E", "CD47", "EOMES",
    "GNLY", "GZMA", "GZMB", "PRF1", "IFNG", "CD8A", "CD8B", "CD95L", "LAMP1",
    "LAG3", "CTLA4", "HLA-DRA", "TNFRSF4", "ICOS", "TNFRSF9", "TNFRSF18",
]

[ModuleScoreCalculator.envs.modules.AntiInflammatory]
features = [
    "TIGIT", "IDO1", "LGALS3", "PDCD1", "FOXP3", "ENTPD1", "CD274", "CSF2", "CTLA4",
    "CXCL12", "CXCL5", "IL8", "MIF", "PTGS2", "VEGFA",
]

[ModuleScoreCalculator.envs.modules.Anergy]
features = [
    "EGR3", "NR4A3", "EGR1", "NR4A2", "EGR2", "TNFSF11", "IRF4", "GCH1", "GADD45B",
    "NFATC1", "JARID2", "SLC29A3", "HLF", "ZFP36L1", "RNF19A", "ADORA2B", "CCRN41",
    "DUSP6", "NDRG1", "ADORA2A", "HSPA1A", "PFKP", "FYN", "CTSE", "ZFP629", "F2R",
    "RNF128", "LAG3", "RGS16", "E2F1", "E2F2",
]

[ModuleScoreCalculator.envs.modules.ProInflammatory]
features = [
    "IL1A", "IL1B", "TNF", "IFNG", "TBX21", "CCL3", "CCL4", "PRF1", "GZMA", "GZMB",
    "GZMK", "GZMH", "CD8A", "FASLG", "CCL2", "CCL20", "IL2", "IL6", "IL12a", "IL17a",
    "IL23a", "PTGS2", "TLR4", "TNF",
]

[ModuleScoreCalculator.envs.modules.LipdMediators]
features = [
    "ADIPOQ", "CD137", "AGRP", "ANGPT1", "ANGPT2", "ANGPTL3", "ANGPTL4", "ANGPTL6",
    "BAFF", "BMP4", "CTSD", "CTSS", "CCL2", "CCL5", "RARRES2", "CFD", "CRP", "CXCL8",
    "CD26", "ESM1", "S100A12", "AHSG", "FGF1", "FGF2", "FGF21", "FGF23", "LGALS3",
    "GCG", "GH1", "HGF", "ICAM1", "IGFBP1", "IGFBP2", "IGFBP3", "IGFBP4", "IGFBP6",
    "IGFBP7", "IL1b", "IL6", "IL10", "IL11", "INS", "LEP", "LIF", "NGAL", "MCSF",
    "MIF", "MPO", "GHRL", "GHSR", "LIPE", "LPL", "AGT", "CEBPA", "CFD", "FABP4",
    "FASN", "IRS2", "KLF15", "PPARG", "PPARGC1A", "RETN", "SRT3", "SLC2A4", "SREBF1",
    "ACACB", "AXIN1", "CCND1", "CDK4", "CEBPB", "CEBPD", "DKK1", "E2F1", "FABP4",
    "FASN",
]

[ModuleScoreCalculator.envs.modules.Glycolysis]
features = [
    "ALDOA", "ALDOB", "ALDOC", "BPGM", "ENO1", "ENO2", "GALM", "GCK", "GPI", "HK2",
    "HK3", "PFKL", "PGAM2", "PGK1", "PGK2", "PGM1", "PGM2", "PGM3", "PKLR", "TPI1",
]

[ModuleScoreCalculator.envs.modules.TCACycle]
features = [
    "ACLY", "ACO1", "ACO2", "CS", "DLAT", "DLD", "DLST", "FH", "IDH1", "IDH2", "IDH3A",
    "IDH3B", "IDH3G", "MDH1", "MDH1B", "MDH2", "OGDH", "PC", "PCK1PCK2", "PDHA1",
    "PDHB", "SDHA", "SDHB", "SDHD", "SUCLA2", "SUCLG1", "SUCLG2",
]

[ModuleScoreCalculator.envs.modules.PentosePhosphatePathway]
features = [
    # "6PD",
    "G6PD", "PGLS", "PRPS1", "PRPS1L1", "PRPS2", "RBKS", "RPE", "RPIA", "TALDO1", "TKT",
]

[ModuleScoreCalculator.envs.modules.GlycogenMetabolism]
features = [
    # "HSPA1A/B",
    "NRN1", "FAM129A", "1L23A", "SPRY1", "GADD45B", "HSPA1A", "HSPA1B", "GPNMB",
    "HAVCR2", "SOAT2", "ADAMTS6",
]

[ModuleScoreCalculator.envs.modules.M1MacrophagePolarization]
features = [
    "IL12", "IL23", "TNF", "IL6", "CD86", "MHCII", "IL1B", "MARCO", "iNOS", "CD64",
    "CD80", "CXCR10", "IL23", "CXCL9", "CXCL10", "CXCL11", "CD86", "IL1A", "IL1B",
    "IL6", "TNFa", "MHCII", "CCL5", "IRF5", "IRF1", "CD40", "IDO1", "KYNU", "CCR7",
    "CD45", "CD68", "CD115", "HLA-DR", "CD205", "CD14",
]

[ModuleScoreCalculator.envs.modules.M2MacrophagePolarization]
features = [
    "ARG1", "ARG2", "IL10", "CD32", "CD163", "CD23", "CD200R1", "PDCD1LG2", "PDL1",
    "MARCO", "CSF1R", "CD206", "IL1RN", "IL1R2", "IL4R", "CCL4", "CCL13", "CCL20",
    "CCL17", "CCL18", "CCL22", "CCL24", "LYVE1", "VEGFA", "VEGFB", "VEGFC", "VEGFD",
    "EGF", "CTSA", "CTSB", "CSTC", "CTSD", "TGFB1", "TGFB2", "TGFB3", "MMP14", "MMP19",
    "MMP9", "CLEC7A", "WNT7B", "FASL", "TNFSF12", "TNFSF8", "CD276", "VTCN1", "MSR1",
    "FN1", "IRF4", "CD45", "CD68", "CD115", "HLA-DR", "CD205", "CD14",
]

[ModuleScoreCalculator.envs.modules.CytolyticsEffectorPathway]
features = ["EOMES", "TBX21", "GZMB", "PRF1", "FASL", "GZMH", "GZMA"]

[ModuleScoreCalculator.envs.modules.TypeI_InterferonResponse]
features = [
    "IRF1", "IFIH1", "IFITM3", "DDX58", "IFI44L", "IFI6", "IFITM2", "NAMPT", "OASL",
    "RTP4", "TREX1", "ADAR", "FAM46C", "LY6E", "MCOLN2", "APOBEC3G", "IL15", "ISG15",
    "MX1", "TLR3",
]

[ModuleScoreCalculator.envs.modules.TypeII_InterferonResponse]
features = [
    "IFNG", "CXCL9", "CXCL10", "STAT1", "MHC I", "MHC II", "PD-L1", "P21", "MYC",
    "SMAD7", "IRF1",
]

[ModuleScoreCalculator.envs.modules.Hypoxia_HIF_Regulated]
features = [
    "AL2", "ALDOA", "AM", "BCL2", "BCL2L1", "FOS", "JUN", "SRC", "CBP", "CCR6",
    "CEBPB", "ENOLAS", "FAS", "FASLG", "FKBP52", "GAPDH", "GLUT1", "GLUT3", "CSF2",
    "IFNG", "IFNB1", "IL13", "IL1R1", "IL2RA", "IL4", "IL5", "IL6R", "IL8", "IL10R",
    "IL15R", "ITGA6", "ITK", "JUND", "CLB54", "MAP3K5", "MAP2K1", "MAP2K2", "MIF",
    "NFATC1", "NFKB2", "NFKBIE", "P53", "TGM6", "TNF", "TNFRSF1B", "TRADD", "TRAIL",
    "TRAP1", "VEGF",
]

[ModuleScoreCalculator.envs.modules.TCell_Terminal_Differentiation]
features = ["TIGIT", "PDCD1", "CD274", "CTLA4", "LAG3", "HAVCR2", "CD244", "CD160"]

[ModuleScoreCalculator.envs.modules.G1S]
features = [
    "BRCA1", "BRCA2", "CCNE1", "CCNE2", "CCNG2", "CDC25A", "CDC45", "CDC6", "CDKN1A",
    "CDKN2C", "CDKN3", "DHFR", "E2F1", "E2F5", "H1F0", "H1FNT", "H1FOO", "H1FX",
    "H2AFB1", "H2AFB2", "H2AFB3", "H2AFJ", "H2AFV", "H2AFVP1", "H2AFX", "H2AFY",
    "H2AFY2", "H2AFZ", "H2AFZP1", "H2AFZP2", "H2AFZP3", "H2AFZP4", "H2AFZP5",
    "H2AFZP6", "H2BFM", "H2BFS", "H2BFWT", "H2BFXP", "H3F3A", "H3F3AP1", "H3F3AP2",
    "H3F3B", "H3F3C", "H1-1", "H1-5", "H1-2", "H1-3", "H1-4", "H1-12P", "H3P26", "H1-6",
    "H2AC1", "H2AC4", "H2AC6", "H2AC7", "H2AC8", "H2AC11", "H2AC12", "H2AC13", "H2AC14",
    "H2AC15", "H2AC16", "H2AC17", "H2AC2P", "H2AC3P", "H2AC9P", "H2AC10P", "H2AC5P",
    "H2BC1", "H2BC3", "H2BC4", "H2BC5", "H2BC6", "H2BC7", "H2BC8", "H2BC9", "H2BC10",
    "H2BC11", "H2BC12", "H2BC13", "H2BC14", "H2BC15", "H2BC17", "H2BC2P", "H2BC16P",
    "H3C1", "H3C2", "H3C3", "H3C4", "H3C6", "H3C7", "H3C8", "H3C10", "H3C11", "H3C12",
    "H3C9P", "H4C1", "H4C2", "H4C3", "H4C4", "H4C5", "H4C6", "H4C7", "H4C8", "H4C9",
    "H4C11", "H4C12", "H4C13", "H4C10P", "H2AC18", "H2AC19", "H2AC21", "H2AC20",
    "H2BP1", "H2BP2", "H2BC20P", "H2BC19P", "H2BC21", "H2BC18", "H3C15", "H3C14",
    "H3C13", "H3-7", "H4C14", "H4C15", "H2AC25", "H2BC27P", "H2BC26", "H3-4", "H4C16",
    "MCM2", "MCM6", "MSH2", "NASP", "NPAT", "PCNA", "RRM1", "RRM2", "SLBP", "TYMS",
]

[ModuleScoreCalculator.envs.modules.G2M]
features = [
    "AURKA", "BIRC5", "BUB1", "BUB1B", "CCNA2", "CCNB1", "CCNB2", "CCNF", "CDC20",
    "CDC25B", "CDC25C", "CDK1", "CDKN2D", "CENPA", "CENPF", "CKS2", "KIF20A", "PLK1",
    "RACGAP1", "TOP2A",
]

[SeuratClusterStats.envs.features.DiffusionMapComponents]
features = "DC_1,DC_2,DC_3,DC_4,DC_5"
kind = "violin"
pt-size = 0
plus = "geom_boxplot(width = 0.1, fill = 'white')"
devpars = { width = 1200, height = 800 }

[ClusterMarkers.envs]
use_presto = true

[SeuratClusterStats.envs.mutaters]
BC9_Clonotypes = "top(subset = Patient == 'BC09', n = 8, uniq = F)"
BC10_Clonotypes = "top(subset = Patient == 'BC10', n = 9, uniq = F)"
BC11_Clonotypes = "top(subset = Patient == 'BC11', n = 7, uniq = F)"
BC9_20Clonotypes = "top(subset = Patient == 'BC09', n = 20, uniq = F)"
BC10_20Clonotypes = "top(subset = Patient == 'BC10', n = 20, uniq = F)"
BC11_20Clonotypes = "top(subset = Patient == 'BC11', n = 20, uniq = F)"
All_Clonotypes = "'All Clonotypes'"
All_T_Cells = "'All T Cells'"
descClonotypes = "factor(CDR3.aa, levels = top(n = 0, each = Patient))"

[SeuratClusterStats.envs.dimplots.DiffusionMap]
reduction = "DC"

[SeuratClusterStats.envs.dimplots.UMAP]
reduction = "umap"

[SeuratClusterStats.envs.features.Gene_Signatures_Along_DC1]
kind = "avgheatmap"
features = [
    "ProInflammatory", "CD8TCellActivation", "Treg", "AntiInflammatory", "Anergy",
    "LipdMediators", "Glycolysis", "TCACycle", "PentosePhosphatePathway",
    "GlycogenMetabolism", "M1MacrophagePolarization", "M2MacrophagePolarization",
    "CytolyticsEffectorPathway", "TypeI_InterferonResponse",
    "TypeII_InterferonResponse", "Hypoxia_HIF_Regulated",
    "TCell_Terminal_Differentiation", "G1S", "G2M",
]
cluster_orderby = "mean(DC_1)"
cluster_rows = true

[SeuratClusterStats.envs.features.Gene_Signatures_Along_DC2]
kind = "avgheatmap"
features = [
    "ProInflammatory", "CD8TCellActivation", "Treg", "AntiInflammatory", "Anergy",
    "LipdMediators", "Glycolysis", "TCACycle", "PentosePhosphatePathway",
    "GlycogenMetabolism", "M1MacrophagePolarization", "M2MacrophagePolarization",
    "CytolyticsEffectorPathway", "TypeI_InterferonResponse",
    "TypeII_InterferonResponse", "Hypoxia_HIF_Regulated",
    "TCell_Terminal_Differentiation", "G1S", "G2M",
]
cluster_orderby = "mean(DC_2)"
cluster_rows = true

[SeuratClusterStats.envs.features.Gene_Signatures_Along_DC3]
kind = "avgheatmap"
features = [
    "ProInflammatory", "CD8TCellActivation", "Treg", "AntiInflammatory", "Anergy",
    "LipdMediators", "Glycolysis", "TCACycle", "PentosePhosphatePathway",
    "GlycogenMetabolism", "M1MacrophagePolarization", "M2MacrophagePolarization",
    "CytolyticsEffectorPathway", "TypeI_InterferonResponse",
    "TypeII_InterferonResponse", "Hypoxia_HIF_Regulated",
    "TCell_Terminal_Differentiation", "G1S", "G2M",
]
cluster_orderby = "mean(DC_3)"
cluster_rows = true

[SeuratClusterStats.envs.features."Features on UMAP"]
kind = "feature"
features = ["DC_1", "DC_2", "DC_3", "DC_4", "DC_5", "CD8A", "CD4", "FOXP3"]
ncol = 3
devpars = { width = 1200 }

[SeuratClusterStats.envs.features."Diffusion Components in all T cells"]
kind = "violin"
ident = "All_T_Cells"
features = ["DC_1", "DC_2", "DC_3", "DC_4", "DC_5"]
ncol = 3
devpars = { width = 900, height = 800 }

[SeuratClusterStats.envs.features."Diffusion Components in clusters ordered by mean(DC_1)"]
kind = "violin"
cluster_orderby = "mean(DC_1)"
features = ["DC_1", "DC_2", "DC_3", "DC_4", "DC_5"]
ncol = 3

[SeuratClusterStats.envs.dimplots."Samples on UMAP"]
group-by = "Sample"

[SeuratClusterStats.envs.dimplots."Clonotypes on UMAP (BC9)"]
group-by = "BC9_Clonotypes"
pt-size = 2
na_group = "All BC9 Clonotypes"

[SeuratClusterStats.envs.dimplots."Clonotypes on UMAP (BC10)"]
group-by = "BC10_Clonotypes"
pt-size = 2
na_group = "All BC10 Clonotypes"

[SeuratClusterStats.envs.dimplots."Clonotypes on UMAP (BC11)"]
group-by = "BC11_Clonotypes"
pt-size = 2
na_group = "All BC11 Clonotypes"

[SeuratClusterStats.envs.dimplots."Top 20 Clonotypes on UMAP (BC9)"]
split-by = "BC9_20Clonotypes"
pt-size = 2
ncol = 4
devpars = { width = 1600, height = 1200 }

[SeuratClusterStats.envs.dimplots."Top 20 Clonotypes on UMAP (BC10)"]
split-by = "BC10_20Clonotypes"
pt-size = 2
ncol = 4
devpars = { width = 1600, height = 1200 }

[SeuratClusterStats.envs.dimplots."Top 20 Clonotypes on UMAP (BC11)"]
split-by = "BC11_20Clonotypes"
pt-size = 2
ncol = 4
devpars = { width = 1600, height = 1200 }

[SeuratClusterStats.envs.hists."All Clonotypes along (DC_1)"]
x = "DC_1"
cell-by = "All_Clonotypes"

[SeuratClusterStats.envs.hists."All Clonotypes along (DC_2)"]
x = "DC_2"
cell-by = "All_Clonotypes"

[SeuratClusterStats.envs.hists."All Clonotypes along (DC_3)"]
x = "DC_3"
cell-by = "All_Clonotypes"

[SeuratClusterStats.envs.hists."Top 20 Clonotypes along DC_1 (BC9)"]
x = "DC_1"
ncol = 2
cells_by = "BC9_20Clonotypes"
cells_orderby = "desc(Clones)"
cells_n = 20

[SeuratClusterStats.envs.hists."Top 20 Clonotypes along DC_1 (BC10)"]
x = "DC_1"
ncol = 2
cells_by = "BC10_20Clonotypes"
cells_orderby = "desc(Clones)"
cells_n = 20

[SeuratClusterStats.envs.hists."Top 20 Clonotypes along DC_1 (BC11)"]
x = "DC_1"
ncol = 2
cells_by = "BC11_20Clonotypes"
cells_orderby = "desc(Clones)"
cells_n = 20

[SeuratClusterStats.envs.hists."Top 20 Clonotypes along DC_2"]
x = "DC_2"
each = "Patient"
ncol = 2
cells_by = "All_Clonotypes"
cells_orderby = "desc(Clones)"
cells_n = 20

[SeuratClusterStats.envs.hists."Top 20 Clonotypes along DC_3"]
x = "DC_3"
each = "Patient"
ncol = 2
cells_by = "All_Clonotypes"
cells_orderby = "desc(Clones)"
cells_n = 20

[SeuratClusterStats.envs.hists."Distribution of clonotypes"]
x = "descClonotypes"
each = "Patient"
ncol = 2
plus = "theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())"

[SeuratClusterStats.plugin_opts]
report_paging = 10
